name: sincronizar imagens
on:
  push:
    branches:
      - "main"
    paths:
      - images/**
      - .github/workflows/sinc.yml

jobs:
  sync_images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Sync images to EFS
        run: |
          sudo su -
          sudo apt-get install -y nfs-common
          mkdir /mnt/efs
          chmod 777 /mnt/efs
          sudo mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 ${{ secrets.EFS_ID }}:/ /mnt/efs
          cp -r *.jpg *.png /mnt/efs
